common_rpm_packages:
  - sudo
  - nano
  - tmux
  - bash-completion
  - python3-dnf
frr_stable_rpm_repo_url: "https://rpm.frrouting.org/repo/frr-stable-repo.el9.noarch.rpm"
my_timezone: Europe/Moscow
trusted_ips:
  - 198.51.100.144/28
  - 203.0.113.96/27
additional_trusted_ips:
  - 192.0.2.64/26
all_trusted_ips: "{{ trusted_ips+additional_trusted_ips }}"
